[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'
auto_detect = true

# optional: increase optimizer
optimize = true
optimizer_runs = 200
